### ISSUE TITLE
Variable sized tuples - populateOffsets misses buffer position

### ISSUE THREAD

**Issue by raulcf** [raulcf/SEEPng#28]
populateOffsets creates problems:

Exception in thread "SingleThreadProcessingEngine" java.lang.IllegalArgumentException
    at java.nio.Buffer.position(Buffer.java:244)
    at uk.ac.imperial.lsds.seep.api.data.ITuple.populateOffsets(ITuple.java:198)
    at uk.ac.imperial.lsds.seep.api.data.ITuple.setData(ITuple.java:52)
    at uk.ac.imperial.lsds.seepworker.core.input.NetworkDataStream.pullDataItem(NetworkDataStream.java:93)
    at uk.ac.imperial.lsds.seepworker.core.SingleThreadProcessingEngine$Worker.run(SingleThreadProcessingEngine.java:93)
    at java.lang.Thread.run(Thread.java:745)

**Comment by raulcf** [comment]
caused by some inestabilities in outputbuffer, it affected to any tuple size actually
